//! Zobrist keys, table generated by a `const fn` at compile time.
//! Slice 5.

use crate::Color;
use crate::bitboard::{Bitboard, idx};

const fn xorshift(mut x: u64) -> u64 {
    x ^= x << 17;
    x ^= x >> 7;
    x ^= x << 13;
    x
}

const SEED: u64 = 0x9E37_79B9_7F4A_7C15;

pub(crate) const ZOBRIST: [[u64; 225]; 2] = {
    let mut table = [[0u64; 225]; 2];
    let mut state = SEED;
    let mut i = 0;
    while i < 450 {
        state = xorshift(state);
        table[i / 225][i % 225] = state;
        i += 1;
    }
    table
};

pub(crate) const WHITE_TO_MOVE: u64 = xorshift(ZOBRIST[1][224]);

/// This convention has a single place
fn zobrist_row(color: Color) -> usize {
    match color {
        Color::Black => 0,
        Color::White => 1,
    }
}

/// zobrist key entry for a particular color in a particular cell
/// Note that the cell is the logical index: r * 15 + c
pub(crate) fn key_for(color: Color, cell: usize) -> u64 {
    ZOBRIST[zobrist_row(color)][cell]
}

/// Convention: `WHITE_TO_MOVE` is xor'd to a board's final key, iff WHITE is to move
/// An empty board's site-to-move key is 0
///
/// Only tests consume this today; the from-scratch validation
/// assertion (ch. 13) is the next real consumer.
#[allow(dead_code)]
pub(crate) fn compute_key(blacks: &Bitboard, whites: &Bitboard, to_move: Color) -> u64 {
    let mut key = match to_move {
        Color::Black => 0,
        Color::White => WHITE_TO_MOVE,
    };
    for r in 0..15u8 {
        for c in 0..15u8 {
            let i = idx(r, c); // the stride index
            let cell = r as usize * 15 + c as usize; // the logical index
            if blacks.test(i) {
                key ^= key_for(Color::Black, cell);
            }
            if whites.test(i) {
                key ^= key_for(Color::White, cell);
            }
        }
    }
    key
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bitboard::{Bitboard, idx};
    use crate::{Board, Color, Move};
    use proptest::prelude::{ProptestConfig, prop};
    use proptest::{prop_assert_eq, proptest};
    use std::collections::HashSet;

    #[test]
    fn table_has_no_zeros_and_no_duplicates() {
        let mut seen: HashSet<u64> = HashSet::with_capacity(451);

        for entry in ZOBRIST.into_iter().flatten().chain([WHITE_TO_MOVE]) {
            assert_ne!(!entry, 0);
            assert!(seen.insert(entry), "duplicate table entry {entry:#x}");
        }
    }

    #[test]
    fn key_depends_on_side_to_move() {
        let blacks = Bitboard::EMPTY.with_bit(idx(0, 0));
        let whites = Bitboard::EMPTY.with_bit(idx(7, 7));
        let key_when_black_to_move = compute_key(&blacks, &whites, Color::Black);
        let key_when_white_to_move = compute_key(&blacks, &whites, Color::White);
        assert_ne!(key_when_black_to_move, key_when_white_to_move);
        assert_eq!(
            key_when_black_to_move ^ key_when_white_to_move,
            WHITE_TO_MOVE
        );
    }

    #[test]
    fn new_board_zobrist_key_is_zero() {
        assert_eq!(Board::new().zobrist(), 0);
        let mut b = Board::new();
        b.play(Move::new(1, 1).unwrap()).unwrap();
        b.play(Move::new(1, 2).unwrap()).unwrap();
        assert_eq!(Board::new().zobrist(), from_scratch(&Board::new()));
    }

    #[test]
    fn different_move_orders_reaching_the_same_position_agree() {
        let moves_a = [(5, 4), (3, 3), (5, 3), (2, 2), (5, 2), (1, 1)];
        let moves_b = [(5, 2), (1, 1), (5, 4), (2, 2), (5, 3), (3, 3)];
        let mut a = Board::new();
        let mut b = Board::new();
        for &(r, c) in &moves_a {
            a.play(Move::new(r, c).unwrap()).unwrap();
        }
        for &(r, c) in &moves_b {
            b.play(Move::new(r, c).unwrap()).unwrap();
        }
        assert_eq!(a.stones(Color::Black), b.stones(Color::Black));
        assert_eq!(a.stones(Color::White), b.stones(Color::White));
        assert_eq!(a.zobrist(), b.zobrist());
        assert_eq!(a.zobrist(), from_scratch(&a));
    }

    fn from_scratch(board: &Board) -> u64 {
        compute_key(
            &board.stones(Color::Black),
            &board.stones(Color::White),
            board.to_move(),
        )
    }

    #[test]
    fn undo_everything_restores_the_initial_key() {
        let mut b = Board::new();
        let script = [(1, 2), (3, 5), (6, 5), (6, 1)];
        for &(r, c) in &script {
            b.play(Move::new(r, c).unwrap()).unwrap();
        }
        for _ in &script {
            b.undo();
        }
        assert_eq!(b.zobrist(), 0);
    }

    proptest! {
        #[test]
        fn incremental_matches_from_scratch(cells in prop::collection::vec(0u16..225, 1..=60)) {
            let mut b = Board::new();
            for p in cells {
                let mv = Move::new((p / 15) as u8, (p % 15) as u8).unwrap();
                let before = b.zobrist();
                if b.play(mv).is_ok() {
                    prop_assert_eq!(b.zobrist(), from_scratch(&b));
                } else {
                    prop_assert_eq!(b.zobrist(), before);
                }
            }
        }
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(10_000))]

        #[test]
        fn roundtrip_play_undo_walks(
            ops in prop::collection::vec((0u16..225, 0u8..3), 1..=100)
        ) {
            let mut b = Board::new();
            for (p, coin) in ops {
                if coin == 0 && !b.moves().is_empty() {
                    b.undo();
                } else {
                    let mv = Move::new((p / 15) as u8, (p % 15) as u8).unwrap();
                    let _ = b.play(mv); // may be Occupied/GameOver — fine
                }
                prop_assert_eq!(b.zobrist(), from_scratch(&b));
            }
        }
    }
}
