#!/usr/bin/env python3
"""Generate catalogue.md and index.jsonl from the curated reference database.

All metadata has been verified against OpenAlex, Crossref, or arXiv HTML.
Entries that could not be fully verified are marked "unverified" in the
notes field and omitted from first_use_of claims.
"""
import json

SECTIONS = [
    ("mcts", "MCTS foundations and taxonomy"),
    ("alphago", "AlphaGo line"),
    ("reimplementation", "Industrial reimplementations and engineering"),
    ("gomoku", "Gomoku, threat-space search, and opening rules"),
    ("data", "External data sources for training and puzzles"),
    ("engines", "Open-source Gomoku engines and tools"),
    ("network", "Network architecture and training"),
    ("ratings", "Ratings and optimization"),
    ("local", "Local project documents"),
]

REFS = [
    {
        "id": 'coulom2007mcts',
        "title": 'Efficient Selectivity and Backup Operators in Monte-Carlo Tree Search',
        "authors": ['Rémi Coulom'],
        "year": 2007,
        "venue": 'Computers and Games (CG 2006), Lecture Notes in Computer Science 4630',
        "doi": '10.1007/978-3-540-75538-8_7',
        "url": 'https://doi.org/10.1007/978-3-540-75538-8_7',
        "arxiv": None,
        "abstract": '',
        "why": 'First use of the term "Monte-Carlo Tree Search" (MCTS) and the four-phase select/expand/evaluate/backup loop.',
        "topics": ['mcts', 'taxonomy'],
        "first_use_of": ['MCTS', 'Monte Carlo Tree Search', 'select', 'expand', 'evaluate', 'backup', 'four-phase MCTS'],
        "aliases": ['MCTS', 'Monte Carlo Tree Search', 'select expand evaluate backup', 'Coulom MCTS'],
        "section": 'mcts',
    },
    {
        "id": 'auer2002ucb1',
        "title": 'Finite-time Analysis of the Multiarmed Bandit Problem',
        "authors": ['Peter Auer', 'Nicolò Cesa-Bianchi', 'Paul Fischer'],
        "year": 2002,
        "venue": 'Machine Learning 47(2–3), 235–256',
        "doi": '10.1023/a:1013689704352',
        "url": 'https://doi.org/10.1023/a:1013689704352',
        "arxiv": None,
        "abstract": '',
        "why": 'UCB1: the finite-time upper-confidence-bound bandit algorithm that underlies UCT.',
        "topics": ['bandits', 'selection'],
        "first_use_of": ['UCB1', 'upper confidence bound', 'multi-armed bandit'],
        "aliases": ['UCB1', 'upper confidence bound', 'upper-confidence-bound', 'multi-armed bandit', 'bandit algorithm', 'Auer UCB'],
        "section": 'mcts',
    },
    {
        "id": 'kocsis2006uct',
        "title": 'Bandit Based Monte-Carlo Planning',
        "authors": ['Levente Kocsis', 'Csaba Szepesvári'],
        "year": 2006,
        "venue": 'European Conference on Machine Learning (ECML 2006), Lecture Notes in Computer Science 4212',
        "doi": '10.1007/11871842_29',
        "url": 'https://doi.org/10.1007/11871842_29',
        "arxiv": None,
        "abstract": '',
        "why": 'UCT: applies the UCB1 bandit formula to tree search.',
        "topics": ['mcts', 'selection'],
        "first_use_of": ['UCT', 'Upper Confidence bounds applied to Trees'],
        "aliases": ['UCT', 'Upper Confidence bounds applied to Trees', 'UCB applied to trees', 'bandit based Monte Carlo planning'],
        "section": 'mcts',
    },
    {
        "id": 'rosin2011puct',
        "title": 'Multi-armed bandits with episode context',
        "authors": ['Christopher D. Rosin'],
        "year": 2011,
        "venue": 'Annals of Mathematics and Artificial Intelligence 61(3), 203–230',
        "doi": '10.1007/s10472-011-9258-6',
        "url": 'https://doi.org/10.1007/s10472-011-9258-6',
        "arxiv": None,
        "abstract": '',
        "why": 'PUCT: polynomial/predictor UCT that incorporates a prior into the exploration bonus; the formula later used by AlphaGo Zero.',
        "topics": ['mcts', 'selection'],
        "first_use_of": ['PUCT', 'predictor UCT', 'polynomial UCT', 'P-UCT'],
        "aliases": ['PUCT', 'predictor UCT', 'polynomial UCT', 'P-UCT', 'prior UCT', 'episode context'],
        "section": 'mcts',
    },
    {
        "id": 'gelly2007rave',
        "title": 'Combining online and offline knowledge in UCT',
        "authors": ['Sylvain Gelly', 'David Silver'],
        "year": 2007,
        "venue": 'Proceedings of the 24th International Conference on Machine Learning (ICML 2007)',
        "doi": '10.1145/1273496.1273531',
        "url": 'https://doi.org/10.1145/1273496.1273531',
        "arxiv": None,
        "abstract": '',
        "why": 'RAVE/AMAF: rapid action value estimation using all moves as first.',
        "topics": ['mcts', 'selection'],
        "first_use_of": ['RAVE', 'AMAF', 'rapid action value estimation', 'all moves as first'],
        "aliases": ['RAVE', 'AMAF', 'rapid action value estimation', 'all moves as first', 'Gelly Silver RAVE'],
        "section": 'mcts',
        "link_unverified": True,
    },
    {
        "id": 'gelly2011rave',
        "title": 'Monte-Carlo tree search and rapid action value estimation in computer Go',
        "authors": ['Sylvain Gelly', 'David Silver'],
        "year": 2011,
        "venue": 'Artificial Intelligence 175(11), 1856–1875',
        "doi": '10.1016/j.artint.2011.03.007',
        "url": 'https://doi.org/10.1016/j.artint.2011.03.007',
        "arxiv": None,
        "abstract": '',
        "why": 'Definitive journal treatment of RAVE in computer Go; part of the MoGo/CrazyStone lineage.',
        "topics": ['mcts', 'go'],
        "first_use_of": ['RAVE'],
        "aliases": ['RAVE', 'rapid action value estimation', 'MoGo', 'Crazy Stone', 'Gelly Silver 2011'],
        "section": 'mcts',
    },
    {
        "id": 'chaslot2008parallel',
        "title": 'Parallel Monte-Carlo Tree Search',
        "authors": ['Guillaume Chaslot', 'Mark H. M. Winands', 'H. Jaap van den Herik'],
        "year": 2008,
        "venue": 'Computers and Games (CG 2008), Lecture Notes in Computer Science 5131',
        "doi": '10.1007/978-3-540-87608-3_6',
        "url": 'https://doi.org/10.1007/978-3-540-87608-3_6',
        "arxiv": None,
        "abstract": '',
        "why": 'Virtual loss and the parallel-MCTS taxonomy (root/leaf/tree parallelization).',
        "topics": ['mcts', 'parallel'],
        "first_use_of": ['virtual loss', 'parallel MCTS', 'tree parallelization', 'leaf parallelization', 'root parallelization'],
        "aliases": ['virtual loss', 'parallel MCTS', 'root parallelization', 'leaf parallelization', 'tree parallelization', 'APV-MCTS', 'asynchronous parallel'],
        "section": 'mcts',
    },
    {
        "id": 'browne2012survey',
        "title": 'A Survey of Monte Carlo Tree Search Methods',
        "authors": ['Cameron Browne', 'Edward J. Powley', 'Daniel Whitehouse', 'Simon M. Lucas', 'Peter I. Cowling', 'Philipp Rohlfshagen', 'Stephen Tavener', 'Diego Pérez', 'Spyridon Samothrakis', 'Simon Colton'],
        "year": 2012,
        "venue": 'IEEE Transactions on Computational Intelligence and AI in Games 4(1), 1–43',
        "doi": '10.1109/tciaig.2012.2186810',
        "url": 'https://doi.org/10.1109/tciaig.2012.2186810',
        "arxiv": None,
        "abstract": '',
        "why": 'Standard survey: MCTS phases, selection enhancements, rollouts, parallelization.',
        "topics": ['mcts', 'survey'],
        "first_use_of": [],
        "aliases": ['MCTS survey', 'Browne survey', 'Monte Carlo Tree Search survey'],
        "section": 'mcts',
        "link_unverified": True,
    },
    {
        "id": 'coulom2007elo',
        "title": 'Computing "Elo Ratings" of Move Patterns in the Game of Go',
        "authors": ['Rémi Coulom'],
        "year": 2007,
        "venue": 'ICGA Journal 30(4), 198–208',
        "doi": '10.3233/icg-2007-30403',
        "url": 'https://doi.org/10.3233/icg-2007-30403',
        "arxiv": None,
        "abstract": '',
        "why": 'Elo estimation for move patterns; background for the rating ideas later used in MCTS priors.',
        "topics": ['go', 'ratings'],
        "first_use_of": [],
        "aliases": ['Elo ratings move patterns', 'Coulom Elo patterns', 'move pattern rating'],
        "section": 'ratings',
        "link_unverified": True,
    },
    {
        "id": 'coulom2012clop',
        "title": 'CLOP: Confident Local Optimization for Noisy Black-Box Parameter Tuning',
        "authors": ['Rémi Coulom'],
        "year": 2012,
        "venue": 'Advances in Computer Games (ACG 2011), Lecture Notes in Computer Science 7168',
        "doi": '10.1007/978-3-642-31866-5_13',
        "url": 'https://doi.org/10.1007/978-3-642-31866-5_13',
        "arxiv": None,
        "abstract": '',
        "why": 'CLOP: parameter tuning with noisy evaluations; relevant if we later tune c_puct or other constants.',
        "topics": ['optimization', 'tuning'],
        "first_use_of": ['CLOP'],
        "aliases": ['CLOP', 'confident local optimization', 'noisy black-box parameter tuning'],
        "section": 'ratings',
    },
    {
        "id": 'segal2011parallel',
        "title": 'On the Scalability of Parallel UCT',
        "authors": ['Richard Segal'],
        "year": 2011,
        "venue": 'Computers and Games (CG 2010), Lecture Notes in Computer Science 6515',
        "doi": '10.1007/978-3-642-17928-0_4',
        "url": 'https://doi.org/10.1007/978-3-642-17928-0_4',
        "arxiv": None,
        "abstract": '',
        "why": 'Analysis of virtual loss and lock-free parallel UCT scaling.',
        "topics": ['mcts', 'parallel'],
        "first_use_of": ['virtual loss'],
        "aliases": ['parallel UCT', 'lock-free parallel UCT', 'virtual loss scaling', 'Segal parallel'],
        "section": 'mcts',
    },
    {
        "id": 'enzenberger2010fuego',
        "title": 'Fuego—An Open-Source Framework for Board Games and Go Engine Based on Monte Carlo Tree Search',
        "authors": ['Markus Enzenberger', 'Martin Müller', 'Broderick Arneson', 'Richard Segal'],
        "year": 2010,
        "venue": 'IEEE Transactions on Computational Intelligence and AI in Games 2(4), 259–269',
        "doi": '10.1109/tciaig.2010.2083662',
        "url": 'https://doi.org/10.1109/tciaig.2010.2083662',
        "arxiv": None,
        "abstract": '',
        "why": 'Open-source MCTS Go engine; engineering context for tree parallelization and the Fuego framework.',
        "topics": ['mcts', 'go'],
        "first_use_of": ['Fuego'],
        "aliases": ['Fuego', 'open-source Go engine', 'Monte Carlo Go engine'],
        "section": 'mcts',
        "link_unverified": True,
    },
    {
        "id": 'winands2008solver',
        "title": 'Monte-Carlo Tree Search Solver',
        "authors": ['Mark H. M. Winands', 'Yngvi Björnsson', 'Jahn-Takeshi Saito'],
        "year": 2008,
        "venue": 'Computers and Games (CG 2008), Lecture Notes in Computer Science 5131',
        "doi": '10.1007/978-3-540-87608-3_3',
        "url": 'https://doi.org/10.1007/978-3-540-87608-3_3',
        "arxiv": None,
        "abstract": '',
        "why": 'MCTS-Solver: propagating proven wins/losses in MCTS, the exact-terminal-value technique we use.',
        "topics": ['mcts', 'solver'],
        "first_use_of": ['MCTS-Solver', 'MCTS solver', 'proven win propagation'],
        "aliases": ['MCTS-Solver', 'MCTS solver', 'solver MCTS', 'proven terminal value', 'exact terminal value'],
        "section": 'mcts',
    },
    {
        "id": 'wang2007uctpatterns',
        "title": 'Modifications of UCT and Sequence-Like Simulations for Monte-Carlo Go',
        "authors": ['Yizao Wang', 'Sylvain Gelly'],
        "year": 2007,
        "venue": 'IEEE Symposium on Computational Intelligence and Games (CIG 2007)',
        "doi": '10.1109/cig.2007.368095',
        "url": 'https://doi.org/10.1109/cig.2007.368095',
        "arxiv": None,
        "abstract": '',
        "why": 'Adds pattern-based priors to UCT selection in Go; ancestor of the neural-network prior used in AlphaGo.',
        "topics": ['mcts', 'go'],
        "first_use_of": ['UCT with patterns', 'pattern prior'],
        "aliases": ['UCT with patterns', 'pattern prior', 'sequence-like simulations', 'Wang Gelly UCT'],
        "section": 'mcts',
        "link_unverified": True,
    },
    {
        "id": 'chaslot2008progressive',
        "title": 'Progressive Strategies for Monte-Carlo Tree Search',
        "authors": ['Guillaume Chaslot', 'Mark H. M. Winands', 'Jaap W. H. M. Uiterwijk'],
        "year": 2008,
        "venue": 'New Mathematics and Natural Computation 4(3), 343–357',
        "doi": '10.1142/s1793005708001094',
        "url": 'https://doi.org/10.1142/s1793005708001094',
        "arxiv": None,
        "abstract": '',
        "why": 'Progressive bias and progressive widening: classical MCTS heuristics catalogued in our exclusions.',
        "topics": ['mcts', 'selection'],
        "first_use_of": ['progressive bias', 'progressive widening'],
        "aliases": ['progressive bias', 'progressive widening', 'progressive strategies'],
        "section": 'mcts',
        "link_unverified": True,
    },
    {
        "id": 'silver2016alphago',
        "title": 'Mastering the game of Go with deep neural networks and tree search',
        "authors": ['David Silver', 'Aja Huang', 'Chris J. Maddison', 'Arthur Guez', 'Laurent Sifre', 'George van den Driessche', 'Julian Schrittwieser', 'Ioannis Antonoglou', 'Veda Panneershelvam', 'Marc Lanctot', 'Sander Dieleman', 'Dominik Grewe', 'John Nham', 'Nal Kalchbrenner', 'Ilya Sutskever', 'Timothy Lillicrap', 'Madeleine Leach', 'Koray Kavukcuoglu', 'Thore Graepel', 'Demis Hassabis'],
        "year": 2016,
        "venue": 'Nature 529, 484–489',
        "doi": '10.1038/nature16961',
        "url": 'https://doi.org/10.1038/nature16961',
        "arxiv": None,
        "abstract": '',
        "why": 'AlphaGo: neural network priors + MCTS + rollout policy, the first superhuman Go program.',
        "topics": ['alphago', 'go'],
        "first_use_of": ['AlphaGo', 'policy network', 'value network', 'rollout policy'],
        "aliases": ['AlphaGo', 'policy network', 'value network', 'rollout policy', 'deep neural networks tree search'],
        "section": 'alphago',
    },
    {
        "id": 'silver2017agz',
        "title": 'Mastering the game of Go without human knowledge',
        "authors": ['David Silver', 'Julian Schrittwieser', 'Karen Simonyan', 'Ioannis Antonoglou', 'Aja Huang', 'Arthur Guez', 'Thomas Hubert', 'Lucas Baker', 'Matthew Lai', 'Adrian Bolton', 'Yutian Chen', 'Timothy Lillicrap', 'Fan Hui', 'Laurent Sifre', 'George van den Driessche', 'Thore Graepel', 'Demis Hassabis'],
        "year": 2017,
        "venue": 'Nature 550, 354–359',
        "doi": '10.1038/nature24270',
        "url": 'https://doi.org/10.1038/nature24270',
        "arxiv": None,
        "abstract": '',
        "why": 'AlphaGo Zero: self-play only, no human data; root Dirichlet noise, temperature sampling, resignation thresholding, tree reuse.',
        "topics": ['alphago', 'self-play'],
        "first_use_of": ['AlphaGo Zero', 'root Dirichlet noise', 'Dirichlet noise', 'temperature sampling', 'resignation threshold', 'tree reuse'],
        "aliases": ['AlphaGo Zero', 'AGZ', 'root Dirichlet noise', 'Dirichlet noise', 'temperature', 'temperature sampling', 'resignation', 'tree reuse'],
        "section": 'alphago',
    },
    {
        "id": 'silver2018alphazero',
        "title": 'Mastering Chess and Shogi by Self-Play with a General Reinforcement Learning Algorithm',
        "authors": ['David Silver', 'Thomas Hubert', 'Julian Schrittwieser', 'Ioannis Antonoglou', 'Matthew Lai', 'Arthur Guez', 'Marc Lanctot', 'Laurent Sifre', 'Dharshan Kumaran', 'Thore Graepel', 'Timothy Lillicrap', 'Karen Simonyan', 'Demis Hassabis'],
        "year": 2018,
        "venue": 'Science 362(6419), 1140–1144',
        "doi": '10.1126/science.aar6404',
        "url": 'https://doi.org/10.1126/science.aar6404',
        "arxiv": '1712.01815',
        "abstract": 'The game of chess is the most widely-studied domain in the history of artificial intelligence. The strongest programs are based on a combination of sophisticated search techniques, domain-specific adaptations, and handcrafted evaluation functions that have been refined by human experts over several decades. In contrast, the AlphaGo Zero program recently achieved superhuman performance in the game of Go, by tabula rasa reinforcement learning from games of self-play. In this paper, we generalise this approach into a single AlphaZero algorithm that can achieve, tabula rasa, superhuman performance in many challenging domains. Starting from random play, and given no domain knowledge except the game rules, AlphaZero achieved within 24 hours a superhuman level of play in the games of chess and shogi (Japanese chess) as well as Go, and convincingly defeated a world-champion program in each case.',
        "why": 'AlphaZero: generalizes AGZ to chess and shogi; states the Dirichlet alpha heuristic (alpha ≈ 10 / typical legal moves).',
        "topics": ['alphazero', 'general'],
        "first_use_of": ['AlphaZero'],
        "aliases": ['AlphaZero', 'general reinforcement learning algorithm', 'chess shogi Go self-play'],
        "section": 'alphago',
    },
    {
        "id": 'schrittwieser2020muzero',
        "title": 'Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model',
        "authors": ['Julian Schrittwieser', 'Ioannis Antonoglou', 'Thomas Hubert', 'Karen Simonyan', 'Laurent Sifre', 'Simon Schmitt', 'Arthur Guez', 'Edward Lockhart', 'Demis Hassabis', 'Thore Graepel', 'Timothy Lillicrap', 'David Silver'],
        "year": 2020,
        "venue": 'Nature 588, 604–609',
        "doi": '10.1038/s41586-020-03051-4',
        "url": 'https://doi.org/10.1038/s41586-020-03051-4',
        "arxiv": '1911.08265',
        "abstract": 'Constructing agents with planning capabilities has long been one of the main challenges in the pursuit of artificial intelligence. Tree-based planning methods have enjoyed huge success in challenging domains, such as chess and Go, where a perfect simulator is available. However, in real-world problems the dynamics governing the environment are often complex and unknown. In this work we present the MuZero algorithm which, by combining a tree-based search with a learned model, achieves superhuman performance in a range of challenging and visually complex domains, without any knowledge of their underlying dynamics. MuZero learns a model that, when applied iteratively, predicts the quantities most directly relevant to planning: the reward, the action-selection policy, and the value function.',
        "why": 'MuZero: model-based planning without knowing the rules; included as context, not implemented.',
        "topics": ['muzero', 'planning'],
        "first_use_of": ['MuZero'],
        "aliases": ['MuZero', 'learned model planning', 'model-based reinforcement learning'],
        "section": 'alphago',
    },
    {
        "id": 'tian2019elf',
        "title": 'ELF OpenGo: An Analysis and Open Reimplementation of AlphaZero',
        "authors": ['Yuandong Tian', 'Jerry Ma', 'Qucheng Gong', 'Shubho Sengupta', 'Zhuoyuan Chen', 'James Pinkerton', 'C. Lawrence Zitnick'],
        "year": 2019,
        "venue": 'Proceedings of the 36th International Conference on Machine Learning (ICML 2019)',
        "doi": None,
        "url": 'https://arxiv.org/abs/1902.04522',
        "arxiv": '1902.04522',
        "abstract": "The AlphaGo, AlphaGo Zero, and AlphaZero series of algorithms are remarkable demonstrations of deep reinforcement learning's capabilities, achieving superhuman performance in the complex game of Go with progressively increasing autonomy. However, many obstacles remain in the understanding of and usability of these promising approaches by the research community. Toward elucidating unresolved mysteries and facilitating future research, we propose ELF OpenGo, an open-source reimplementation of the AlphaZero algorithm. ELF OpenGo is the first open-source Go AI to convincingly demonstrate superhuman performance with a perfect (20:0) record against global top professionals. We apply ELF OpenGo to conduct extensive ablation studies, and to identify and analyze numerous interesting phenomena in both the model training and in the gameplay inference procedures.",
        "why": 'ELF OpenGo: open reimplementation; publishes c_puct = 1.5 and batching/engineering practice.',
        "topics": ['reimplementation', 'engineering'],
        "first_use_of": ['ELF OpenGo', 'c_puct'],
        "aliases": ['ELF OpenGo', 'c_puct', 'exploration constant', 'OpenGo', 'ELF'],
        "section": 'reimplementation',
    },
    {
        "id": 'wu2019katago',
        "title": 'Accelerating Self-Play Learning in Go',
        "authors": ['David J. Wu'],
        "year": 2019,
        "venue": 'arXiv:1902.10565',
        "doi": None,
        "url": 'https://arxiv.org/abs/1902.10565',
        "arxiv": '1902.10565',
        "abstract": "By introducing several improvements to the AlphaZero process and architecture, we greatly accelerate self-play learning in Go, achieving a 50x reduction in computation over comparable methods. Like AlphaZero and replications such as ELF OpenGo and Leela Zero, our bot KataGo only learns from neural-net-guided Monte Carlo tree search self-play. But whereas AlphaZero required thousands of TPUs over several days and ELF required thousands of GPUs over two weeks, KataGo surpasses ELF's final model after only 19 days on fewer than 30 GPUs. Much of the speedup involves non-domain-specific improvements that might directly transfer to other problems.",
        "why": 'KataGo: global pooling, playout-cap randomization, auxiliary targets, forced playouts.',
        "topics": ['reimplementation', 'training'],
        "first_use_of": ['KataGo', 'global pooling', 'playout-cap randomization'],
        "aliases": ['KataGo', 'global pooling', 'playout-cap randomization', 'forced playouts', 'auxiliary targets'],
        "section": 'reimplementation',
    },
    {
        "id": 'cazenave2020polygames',
        "title": 'Polygames: Improved Zero Learning',
        "authors": ['Tristan Cazenave', 'Yen-Chi Chen', 'Guan-Wei Chen', 'Shi-Yu Chen', 'Xian-Dong Chiu', 'Julien Dehos', 'Maria Elsa', 'Qucheng Gong', 'Hengyuan Hu', 'Vasil Khalidov', 'Cheng-Ling Li', 'Hsin-I Lin', 'Yu-Jin Lin', 'Xavier Martinet', 'Vegard Mella', 'Jérémy Rapin', 'Baptiste Rozière', 'Gabriel Synnaeve', 'Fabien Teytaud', 'Olivier Teytaud', 'Shi-Cheng Ye', 'Yi-Jun Ye', 'Shi-Jim Yen', 'Sergey Zagoruyko'],
        "year": 2020,
        "venue": 'ICGA Journal 43(1), 1–17',
        "doi": '10.3233/icg-200157',
        "url": 'https://doi.org/10.3233/icg-200157',
        "arxiv": '2001.09832',
        "abstract": "Since DeepMind's AlphaZero, Zero learning quickly became the state-of-the-art method for many board games. It can be improved using a fully convolutional structure (no fully connected layer). Using such an architecture plus global pooling, we can create bots independent of the board size. The training can be made more robust by keeping track of the best checkpoints during the training and by training against them. Using these features, we release Polygames, our framework for Zero learning, with its library of games and its checkpoints.",
        "why": 'Polygames: general board-game zero-learning framework; planar/hexagonal variants and global pooling.',
        "topics": ['reimplementation', 'framework'],
        "first_use_of": ['Polygames'],
        "aliases": ['Polygames', 'zero learning framework', 'fully convolutional'],
        "section": 'reimplementation',
    },
    {
        "id": 'leelazero',
        "title": 'Leela Zero',
        "authors": ['Gian-Carlo Pascutto (GCP) and contributors'],
        "year": 2017,
        "venue": 'Open-source project',
        "doi": None,
        "url": 'https://zero.sjeng.org/',
        "arxiv": None,
        "abstract": '',
        "why": 'Community AlphaZero reimplementation for Go; the main public baseline for zero-learning engines.',
        "topics": ['reimplementation', 'engineering'],
        "first_use_of": ['Leela Zero'],
        "aliases": ['Leela Zero', 'LeelaZero', 'community AlphaZero'],
        "section": 'reimplementation',
    },
    {
        "id": 'xie2018alphagomoku',
        "title": 'AlphaGomoku: An AlphaGo-based Gomoku Artificial Intelligence using Curriculum Learning',
        "authors": ['Zheng Xie', 'Xingyu Fu', 'JinYuan Yu'],
        "year": 2018,
        "venue": 'arXiv:1809.10595',
        "doi": None,
        "url": 'https://arxiv.org/abs/1809.10595',
        "arxiv": '1809.10595',
        "abstract": "In this project, we combine AlphaGo algorithm with Curriculum Learning to crack the game of Gomoku. Modifications like Double Networks Mechanism and Winning Value Decay are implemented to solve the intrinsic asymmetry and short-sight of Gomoku. Our final AI AlphaGomoku, through two days' training on a single GPU, can achieve a relatively high winning rate against human experts.",
        "why": 'Closest published AlphaZero-style Gomoku agent; curriculum learning for the short-horizon tactical nature of Gomoku.',
        "topics": ['gomoku', 'alphazero'],
        "first_use_of": ['AlphaGomoku'],
        "aliases": ['AlphaGomoku', 'AlphaGo-based Gomoku', 'curriculum learning Gomoku'],
        "section": 'gomoku',
    },
    {
        "id": 'allis1994thesis',
        "title": 'Searching for Solutions in Games and Artificial Intelligence',
        "authors": ['Louis Victor Allis'],
        "year": 1994,
        "venue": 'PhD thesis, Maastricht University',
        "doi": '10.26481/dis.19940923la',
        "url": 'https://doi.org/10.26481/dis.19940923la',
        "arxiv": None,
        "abstract": '',
        "why": 'Origin of threat-space search (TSS); proof that Go-Moku is a first-player win; proof-number search background.',
        "topics": ['gomoku', 'threat-space search'],
        "first_use_of": ['threat-space search', 'TSS', 'Go-Moku', 'proof-number search', 'dependency-based search'],
        "aliases": ['threat-space search', 'TSS', 'Go-Moku', 'proof-number search', 'Allis thesis', 'Searching for Solutions in Games'],
        "section": 'gomoku',
    },
    {
        "id": 'allis1996gomoku',
        "title": 'Go-Moku Solved by New Search Techniques',
        "authors": ['Louis Victor Allis', 'H. Jaap van den Herik', 'M. P. H. Huntjens'],
        "year": 1996,
        "venue": 'Computational Intelligence 12(1), 7–23',
        "doi": '10.1111/j.1467-8640.1996.tb00250.x',
        "url": 'https://doi.org/10.1111/j.1467-8640.1996.tb00250.x',
        "arxiv": None,
        "abstract": '',
        "why": 'Go-Moku solved via threat-space search and proof-number search; companion to the 1994 thesis.',
        "topics": ['gomoku', 'threat-space search'],
        "first_use_of": ['Go-Moku solved', 'threat-space search'],
        "aliases": ['Go-Moku solved', 'Go-Moku new search techniques', 'Allis van den Herik Huntjens'],
        "section": 'gomoku',
        "link_unverified": True,
    },
    {
        "id": 'wu2005connect6',
        "title": 'Connect6',
        "authors": ['I-Chen Wu', 'Dei-Yen Huang', 'Hsiu-Chen Chang'],
        "year": 2005,
        "venue": 'ICGA Journal 28(4), 234–242',
        "doi": '10.3233/icg-2005-28405',
        "url": 'https://doi.org/10.3233/icg-2005-28405',
        "arxiv": None,
        "abstract": '',
        "why": 'Connect6: six-in-a-row connect game; extends Gomoku ideas to a modern variant with opening fairness.',
        "topics": ['gomoku', 'connect6'],
        "first_use_of": ['Connect6'],
        "aliases": ['Connect6', 'Connect 6', 'six-in-a-row'],
        "section": 'gomoku',
        "link_unverified": True,
    },
    {
        "id": 'renjunet',
        "title": 'Renju Rules',
        "authors": ['Renju International Federation'],
        "year": None,
        "venue": 'renju.net',
        "doi": None,
        "url": 'https://renju.net/rules/',
        "arxiv": None,
        "abstract": '',
        "why": 'Official Renju rules and opening terminology; context for Gomoku opening-rule history.',
        "topics": ['gomoku', 'rules'],
        "first_use_of": ['Renju rules'],
        "aliases": ['Renju', 'Renju rules', 'RIF rules', 'forbidden moves', 'opening rules'],
        "section": 'gomoku',
    },
    {
        "id": 'gomocup',
        "title": 'Gomocup: the Gomoku AI Tournament — Detail Information',
        "authors": ['Gomocup organizers'],
        "year": None,
        "venue": 'gomocup.org',
        "doi": None,
        "url": 'https://gomocup.org/detail-information/',
        "arxiv": None,
        "abstract": '',
        "why": 'Gomocup tournament rules: freestyle, standard, renju, caro, balanced openings.',
        "topics": ['gomoku', 'rules'],
        "first_use_of": ['Gomocup', 'freestyle gomoku', 'standard gomoku', 'balanced openings'],
        "aliases": ['Gomocup', 'freestyle gomoku', 'standard gomoku', 'caro', 'balanced openings', 'Piskvork'],
        "section": 'gomoku',
    },
    {
        "id": 'he2016resnet',
        "title": 'Deep Residual Learning for Image Recognition',
        "authors": ['Kaiming He', 'Xiangyu Zhang', 'Shaoqing Ren', 'Jian Sun'],
        "year": 2016,
        "venue": 'Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR 2016)',
        "doi": '10.1109/cvpr.2016.90',
        "url": 'https://doi.org/10.1109/cvpr.2016.90',
        "arxiv": '1512.03385',
        "abstract": 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions. We provide comprehensive empirical evidence showing that these residual networks are easier to optimize, and can gain accuracy from considerably increased depth.',
        "why": 'ResNet: residual blocks with skip connections, the trunk of our value/policy network.',
        "topics": ['network', 'architecture'],
        "first_use_of": ['ResNet', 'residual network', 'residual block', 'skip connection'],
        "aliases": ['ResNet', 'residual network', 'residual block', 'skip connection', 'deep residual learning'],
        "section": 'network',
    },
    {
        "id": 'ioffe2015batchnorm',
        "title": 'Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift',
        "authors": ['Sergey Ioffe', 'Christian Szegedy'],
        "year": 2015,
        "venue": 'arXiv:1502.03167',
        "doi": None,
        "url": 'https://arxiv.org/abs/1502.03167',
        "arxiv": '1502.03167',
        "abstract": "Training Deep Neural Networks is complicated by the fact that the distribution of each layer's inputs changes during training, as the parameters of the previous layers change. This slows down the training by requiring lower learning rates and careful parameter initialization, and makes it notoriously hard to train models with saturating nonlinearities. We refer to this phenomenon as internal covariate shift, and address the problem by normalizing layer inputs.",
        "why": 'Batch normalization, used in the ResNet trunk.',
        "topics": ['network', 'training'],
        "first_use_of": ['batch normalization', 'batch norm', 'internal covariate shift'],
        "aliases": ['batch normalization', 'batch norm', 'BN', 'internal covariate shift'],
        "section": 'network',
    },
    {
        "id": 'schaul2015per',
        "title": 'Prioritized Experience Replay',
        "authors": ['Tom Schaul', 'John Quan', 'Ioannis Antonoglou', 'David Silver'],
        "year": 2015,
        "venue": 'arXiv:1511.05952',
        "doi": None,
        "url": 'https://arxiv.org/abs/1511.05952',
        "arxiv": '1511.05952',
        "abstract": 'Experience replay lets online reinforcement learning agents remember and reuse experiences from the past. In prior work, experience transitions were uniformly sampled from a replay memory. However, this approach simply replays transitions at the same frequency that they were originally experienced, regardless of their significance. In this paper we develop a framework for prioritizing experience, so as to replay important transitions more frequently, and therefore learn more efficiently.',
        "why": 'Prioritized replay sampling; catalogue context for the replay buffer design.',
        "topics": ['training', 'replay'],
        "first_use_of": ['prioritized experience replay', 'prioritized replay'],
        "aliases": ['prioritized experience replay', 'prioritized replay', 'PER', 'importance sampling replay'],
        "section": 'network',
    },
    {
        "id": 'kingma2014adam',
        "title": 'Adam: A Method for Stochastic Optimization',
        "authors": ['Diederik P. Kingma', 'Jimmy Ba'],
        "year": 2014,
        "venue": 'arXiv:1412.6980',
        "doi": None,
        "url": 'https://arxiv.org/abs/1412.6980',
        "arxiv": '1412.6980',
        "abstract": 'We introduce Adam, an algorithm for first-order gradient-based optimization of stochastic objective functions, based on adaptive estimates of lower-order moments. The method is straightforward to implement, is computationally efficient, has little memory requirements, is invariant to diagonal rescaling of the gradients, and is well suited for problems that are large in terms of data and/or parameters.',
        "why": 'Adam optimizer; project training uses AdamW (Adam with decoupled weight decay).',
        "topics": ['training', 'optimization'],
        "first_use_of": ['Adam'],
        "aliases": ['Adam', 'adaptive moment estimation', 'Adam optimizer'],
        "section": 'network',
    },
    {
        "id": 'loshchilov2017adamw',
        "title": 'Decoupled Weight Decay Regularization',
        "authors": ['Ilya Loshchilov', 'Frank Hutter'],
        "year": 2017,
        "venue": 'arXiv:1711.05101',
        "doi": None,
        "url": 'https://arxiv.org/abs/1711.05101',
        "arxiv": '1711.05101',
        "abstract": 'L2 regularization and weight decay regularization are equivalent for standard stochastic gradient descent (when rescaled by the learning rate), but as we demonstrate this is not the case for adaptive gradient algorithms, such as Adam. While common implementations of these algorithms employ L2 regularization, treating it as weight decay, we show that this is fundamentally different.',
        "why": 'AdamW: Adam with decoupled weight decay, the optimizer planned for network training.',
        "topics": ['training', 'optimization'],
        "first_use_of": ['AdamW', 'decoupled weight decay'],
        "aliases": ['AdamW', 'decoupled weight decay', 'Adam with weight decay'],
        "section": 'network',
    },
    {
        "id": 'szegedy2016labelsmoothing',
        "title": 'Rethinking the Inception Architecture for Computer Vision',
        "authors": ['Christian Szegedy', 'Vincent Vanhoucke', 'Sergey Ioffe', 'Jon Shlens', 'Zbigniew Wojna'],
        "year": 2016,
        "venue": 'Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR 2016)',
        "doi": '10.1109/cvpr.2016.308',
        "url": 'https://doi.org/10.1109/cvpr.2016.308',
        "arxiv": '1512.00567',
        "abstract": 'Convolutional networks are at the core of most state-of-the-art computer vision solutions for a wide variety of tasks. Since 2014 very deep convolutional networks started to become mainstream, yielding substantial gains in various benchmarks. Although increased model size and computational cost tend to translate to immediate quality gains, the benefits are not always commensurate with the increase in computational cost.',
        "why": 'Introduces label smoothing and factorized convolutions; catalogue context for training tricks.',
        "topics": ['network', 'training'],
        "first_use_of": ['label smoothing'],
        "aliases": ['label smoothing', 'Inception v3', 'factorized convolutions', 'Rethinking Inception'],
        "section": 'network',
    },
    {
        "id": 'elo1978',
        "title": 'The Rating of Chessplayers, Past and Present',
        "authors": ['Arpad E. Elo'],
        "year": 1978,
        "venue": 'Batsford (book)',
        "doi": None,
        "url": 'https://ci.nii.ac.jp/ncid/BB18462776',
        "arxiv": None,
        "abstract": '',
        "why": 'The Elo rating system used for arena strength measurement.',
        "topics": ['ratings'],
        "first_use_of": ['Elo rating', 'Elo rating system'],
        "aliases": ['Elo', 'Elo rating', 'Elo rating system', 'Arpad Elo'],
        "unverified": True,
        "section": 'ratings',
        "link_unverified": True,
    },
    {
        "id": 'silver2017agzsupplementary',
        "title": 'AlphaGo Zero — Supplementary Information',
        "authors": ['David Silver et al.'],
        "year": 2017,
        "venue": 'Nature 550 (supplementary methods)',
        "doi": '10.1038/nature24270',
        "url": 'https://www.nature.com/articles/nature24270',
        "arxiv": None,
        "abstract": '',
        "why": 'Supplementary methods for AlphaGo Zero: network architecture, hyperparameters, self-play pipeline details.',
        "topics": ['alphago', 'self-play'],
        "first_use_of": [],
        "aliases": ['AlphaGo Zero supplementary', 'AGZ supplementary', 'AlphaGo Zero methods'],
        "section": 'alphago',
    },
    {
        "id": 'burn021docs',
        "title": 'Burn v0.21.0 API Documentation',
        "authors": ['Trace-AI (Burn maintainers)'],
        "year": 2024,
        "venue": 'Local/docs (crate docs)',
        "doi": None,
        "url": 'https://docs.rs/burn/0.21.0/burn/index.html',
        "arxiv": None,
        "abstract": '',
        "why": 'Canonical API reference for the pinned Burn version used in the project.',
        "topics": ['local', 'burn'],
        "first_use_of": [],
        "aliases": ['Burn 0.21.0', 'Burn docs', 'Burn API'],
        "section": 'local',
    },
    {
        "id": 'doc12architecture',
        "title": 'Chapter 12 — Gomoku Architecture',
        "authors": ['rust-ml project'],
        "year": None,
        "venue": 'Local/docs',
        "doi": None,
        "url": 'docs/12-gomoku-architecture.md',
        "arxiv": None,
        "abstract": '',
        "why": 'System design, milestone plan, crate boundaries, claim-label conventions, and honesty ledger.',
        "topics": ['local', 'project'],
        "first_use_of": [],
        "aliases": ['chapter 12', 'Gomoku architecture', 'system design', 'honesty ledger'],
        "section": 'local',
    },
    {
        "id": 'doc13engine',
        "title": 'Chapter 13 — Engine Design',
        "authors": ['rust-ml project'],
        "year": None,
        "venue": 'Local/docs',
        "doi": None,
        "url": 'docs/13-engine-design.md',
        "arxiv": None,
        "abstract": '',
        "why": 'Engine design and locked decisions: freestyle overlines, Swap2, 17×17 encoding, absolute colors.',
        "topics": ['local', 'project'],
        "first_use_of": [],
        "aliases": ['chapter 13', 'engine design', 'locked decisions'],
        "section": "local",
    },
    {
        "id": 'gomocup-results-archives',
        "title": 'Gomocup tournament result archives (2000–2026)',
        "authors": ['Gomocup organizers'],
        "year": None,
        "venue": 'gomocup.org',
        "doi": None,
        "url": 'https://gomocup.org/results/',
        "arxiv": None,
        "abstract": '',
        "why": 'Yearly ZIP archives of Gomocup tournament games in PSQ format, plus balanced opening files for freestyle, standard, caro and renju rulesets.',
        "topics": ['data', 'games', 'openings', 'gomocup'],
        "first_use_of": [],
        "aliases": ['Gomocup archives', 'PSQ', 'Piskvorky game records', 'Gomocup results', 'freestyle15 openings'],
        "section": 'data',
    },
    {
        "id": 'piskvork-openings',
        "title": 'Piskvork openings.txt',
        "authors": ['Petr Lastovicka (plastovicka)'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://raw.githubusercontent.com/plastovicka/Piskvork/master/openings.txt',
        "arxiv": None,
        "abstract": '',
        "why": 'Small, clean Swap2 opening catalogue shipped with the Piskvork tournament manager: 41 lines of comma-separated (x,y) coordinate pairs relative to the board centre.',
        "topics": ['data', 'openings', 'piskvork'],
        "first_use_of": [],
        "aliases": ['Piskvork openings', 'openings.txt', 'Swap2 opening book', 'Gomocup opening format'],
        "section": 'data',
    },
    {
        "id": 'renju-net-swap2-rule',
        "title": 'International Rules of Gomoku — Swap2',
        "authors": ['Renju International Federation'],
        "year": None,
        "venue": 'renju.net',
        "doi": None,
        "url": 'https://www.renju.net/gomokurules/',
        "arxiv": None,
        "abstract": '',
        "why": "Authoritative HTML description of the Swap2 opening protocol and the international Gomoku rule set. Note: RIF Gomoku rules treat overlines as non-winning, unlike the project's freestyle ruleset.",
        "topics": ['data', 'rules', 'swap2', 'renju'],
        "first_use_of": [],
        "aliases": ['Renju Swap2', 'RIF Gomoku rules', 'international Gomoku rules', 'Swap2 opening rule'],
        "section": 'data',
    },
    {
        "id": 'hf-karesis-gomoku',
        "title": 'Karesis / Gomoku (Five in a Row) AI Dataset',
        "authors": ['Karesis'],
        "year": None,
        "venue": 'Hugging Face Datasets',
        "doi": '10.57967/hf/4816',
        "url": 'https://huggingface.co/datasets/Karesis/Gomoku',
        "arxiv": None,
        "abstract": '',
        "why": 'MIT-licensed HuggingFace dataset: 875 self-play games / 26,378 15×15 board-state/next-move positions generated with the WinePy alpha-beta engine.',
        "topics": ['data', 'games', 'huggingface'],
        "first_use_of": [],
        "aliases": ['Karesis Gomoku', 'HF Karesis Gomoku', 'Gomoku AI dataset', 'WinePy self-play'],
        "section": 'data',
    },
    {
        "id": 'hf-poolc-gomoku-1.8m',
        "title": 'PoolC / gomoku-dataset-1.8M',
        "authors": ['PoolC'],
        "year": None,
        "venue": 'Hugging Face Datasets',
        "doi": None,
        "url": 'https://huggingface.co/datasets/PoolC/gomoku-dataset-1.8M',
        "arxiv": None,
        "abstract": '',
        "why": 'Large HuggingFace dataset of 1.88M tokenized Gomoku positions in a single Parquet file. License and encoding are undocumented; unusable without reverse-engineering the input_ids sequence.',
        "topics": ['data', 'games', 'huggingface'],
        "first_use_of": [],
        "aliases": ['PoolC gomoku dataset', 'HF PoolC', 'gomoku-dataset-1.8M', '1.8M gomoku'],
        "section": 'data',
    },
    {
        "id": 'banbu-vcf-material',
        "title": 'banbu-gomoku VCF material',
        "authors": ['gugujiao953-ship-it'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://raw.githubusercontent.com/gugujiao953-ship-it/banbu-gomoku/main/public/puzzles/vcf-material.json',
        "arxiv": None,
        "abstract": '',
        "why": '763 labelled VCF (victory by continuous four) puzzles with explicit solution lines. The only verified public set found that ships answers; ruleset must be re-verified for freestyle overlines-win.',
        "topics": ['data', 'puzzles', 'vcf'],
        "first_use_of": [],
        "aliases": ['banbu VCF', 'vcf-material.json', 'VCF puzzles with solutions', 'Gomoku VCF material'],
        "section": 'data',
    },
    {
        "id": 'banbu-kaibao-vcf',
        "title": 'banbu-gomoku 开宝实战VCF',
        "authors": ['gugujiao953-ship-it'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://raw.githubusercontent.com/gugujiao953-ship-it/banbu-gomoku/main/public/puzzles/kaibao/%E5%AE%9E%E6%88%98VCF_1052%E9%A2%98.json',
        "arxiv": None,
        "abstract": '',
        "why": '~1050 VCF puzzle positions imported from the Kaibao Android app. No stored answers; Renju-oriented; requires an internal solver to produce labels.',
        "topics": ['data', 'puzzles', 'vcf'],
        "first_use_of": [],
        "aliases": ['banbu kaibao VCF', '开宝实战VCF', 'Kaibao Gomoku VCF'],
        "section": 'data',
    },
    {
        "id": 'banbu-renju-portal-vcf',
        "title": 'banbu-gomoku RenjuPortal VCF collection',
        "authors": ['gugujiao953-ship-it'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://raw.githubusercontent.com/gugujiao953-ship-it/banbu-gomoku/main/public/puzzles/kaibao/RenjuPortalVCF.json',
        "arxiv": None,
        "abstract": '',
        "why": '4,024 VCF puzzle positions from RenjuPortal. No stored solution lines; Renju-oriented; requires ruleset conversion before use in freestyle Gomoku.',
        "topics": ['data', 'puzzles', 'vcf'],
        "first_use_of": [],
        "aliases": ['banbu RenjuPortal VCF', 'RenjuPortal VCF', 'RenjuPortal puzzles'],
        "section": 'data',
    },
    {
        "id": 'lfz-renju-puzzles',
        "title": 'lfz084 / renju puzzle JSON archive',
        "authors": ['lfz084'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/lfz084/renju/tree/master/puzzle/json',
        "arxiv": None,
        "abstract": '',
        "why": 'Large collection of Renju puzzle sets (黑先VCF, 白先VCF, mate-in-3, exercises). Thousands of positions but no explicit answers; strong Renju bias and forbidden-hand conventions.',
        "topics": ['data', 'puzzles', 'vcf', 'vct', 'renju'],
        "first_use_of": [],
        "aliases": ['lfz084 renju puzzles', 'Renju puzzle JSON', 'VCF puzzle archive', 'mate-in-3 puzzles'],
        "section": 'data',
    },
    {
        "id": 'renju-benchmark-puzzles',
        "title": 'renju-benchmark synthetic tactical tests',
        "authors": ['Tk-visionary'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://raw.githubusercontent.com/Tk-visionary/renju-benchmark/main/data/puzzles.jsonl',
        "arxiv": None,
        "abstract": '',
        "why": 'GPL-3.0 set of 8 hand-authored labelled Renju positions (exact-five, overline, forbidden moves, must-block). Small correctness/edge-case test set, not a large training corpus.',
        "topics": ['data', 'puzzles', 'renju'],
        "first_use_of": [],
        "aliases": ['renju-benchmark', 'Renju tactical benchmark', 'Renju edge cases'],
        "section": 'data',
    },
    {
        "id": 'hf-maojh15-gomoku-zero',
        "title": 'maojh15 / GomokuZeroAI',
        "authors": ['maojh15'],
        "year": None,
        "venue": 'Hugging Face Models',
        "doi": None,
        "url": 'https://huggingface.co/maojh15/GomokuZeroAI',
        "arxiv": None,
        "abstract": '',
        "why": 'MIT-licensed AlphaZero-style Gomoku policy-value checkpoint for 15×15. Could serve as a sparring partner or synthetic-data generator, or as an initialization for transfer learning.',
        "topics": ['data', 'models', 'huggingface', 'alphazero'],
        "first_use_of": [],
        "aliases": ['GomokuZeroAI', 'maojh15 GomokuZeroAI', 'HF GomokuZeroAI'],
        "section": 'data',
    },
    {
        "id": 'hf-nagi-ovo-alphazero-gomoku',
        "title": 'Nagi-ovo / alphazero-gomoku',
        "authors": ['Nagi-ovo'],
        "year": None,
        "venue": 'Hugging Face Models',
        "doi": None,
        "url": 'https://huggingface.co/Nagi-ovo/alphazero-gomoku',
        "arxiv": None,
        "abstract": '',
        "why": 'MIT-licensed AlphaZero-style Gomoku model checkpoint trained for the same-named GitHub project. Potential sparring partner or pretrained initialization; verify board size and ruleset.',
        "topics": ['data', 'models', 'huggingface', 'alphazero'],
        "first_use_of": [],
        "aliases": ['Nagi-ovo alphazero-gomoku', 'HF alphazero-gomoku', 'alphazero-gomoku model'],
        "section": 'data',
    },
    {
        "id": 'rapfi',
        "title": 'Rapfi — strong open-source Gomoku/Renju engine',
        "authors": ['dhbloo'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/dhbloo/rapfi',
        "arxiv": None,
        "abstract": '',
        "why": 'Modern alpha-beta + NNUE engine and one of the strongest public Gomoku programs. Supports selfplay mode that outputs training samples and an opengen mode for balanced openings. GPL-3.0 (engine); network weights are CC0-1.0.',
        "topics": ['engine', 'sparring', 'data generator', 'rapfi'],
        "first_use_of": [],
        "aliases": ['Rapfi', 'dhbloo Rapfi', 'Rapfi engine', 'Rapfi selfplay'],
        "section": 'engines',
    },
    {
        "id": 'alphagomoku-engine',
        "title": 'AlphaGomoku — AlphaZero-style Gomoku engine',
        "authors": ['Maciej Kozarzewski'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/MaciejKozarzewski/AlphaGomoku',
        "arxiv": None,
        "abstract": '',
        "why": 'Full C++ AlphaZero implementation for Gomoku with MCTS, neural networks, selfplay and training front-ends. Supports Swap2 and other opening controllers. GPL-3.0.',
        "topics": ['engine', 'sparring', 'data generator', 'alphagomoku'],
        "first_use_of": [],
        "aliases": ['AlphaGomoku engine', 'MaciejKozarzewski AlphaGomoku', 'AlphaZero Gomoku engine'],
        "section": 'engines',
    },
    {
        "id": 'katagomo',
        "title": 'KataGomo — KataGo fork for Gomoku and Renju',
        "authors": ['hzyhhzy'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/hzyhhzy/KataGomo',
        "arxiv": None,
        "abstract": '',
        "why": 'KataGo derivative trained for Gomoku (freestyle, standard) and Renju. Strong open-source engine with pre-trained network releases and KataGo selfplay/training scripts. Custom MIT-style license.',
        "topics": ['engine', 'sparring', 'data generator', 'katagomo'],
        "first_use_of": [],
        "aliases": ['KataGomo', 'hzyhhzy KataGomo', 'KataGo Gomoku'],
        "section": 'engines',
    },
    {
        "id": 'c-gomoku-cli',
        "title": 'c-gomoku-cli — head-to-head match runner for Gomocup engines',
        "authors": ['nkg114mc'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/nkg114mc/c-gomoku-cli',
        "arxiv": None,
        "abstract": '',
        "why": 'Command-line tournament manager that runs any Gomocup-protocol engines, supports fixed opening files and concurrent games, and writes SGF plus CSV/binary training samples. GPL-3.0.',
        "topics": ['engine', 'data generator', 'orchestration', 'c-gomoku-cli'],
        "first_use_of": [],
        "aliases": ['c-gomoku-cli', 'Gomocup CLI', 'Gomoku match runner', 'Gomoku SGF generator'],
        "section": 'engines',
    },
    {
        "id": 'rapfi-gomocup-legacy',
        "title": 'Rapfi-gomocup — legacy Gomocup freestyle engine',
        "authors": ['dhbloo'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/dhbloo/Rapfi-gomocup',
        "arxiv": None,
        "abstract": '',
        "why": 'Older MIT-licensed Rapfi that participated in Gomocup 2018. Speaks the Gomocup protocol and can be driven by c-gomoku-cli or Piskvork. Weaker than current Rapfi but permissively licensed.',
        "topics": ['engine', 'sparring', 'rapfi'],
        "first_use_of": [],
        "aliases": ['Rapfi-gomocup', 'legacy Rapfi', 'Rapfi 2018'],
        "section": 'engines',
    },
    {
        "id": 'slowrenju',
        "title": 'SlowRenju — Gomoku/Renju alpha-beta engine',
        "authors": ['wind23'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/wind23/SlowRenju',
        "arxiv": None,
        "abstract": '',
        "why": 'Iterative-deepening alpha-beta engine that has competed in Gomocup since 2013. Supports freestyle, standard and renju on board sizes 5–20. GPL-3.0; useful mid-tier sparring partner.',
        "topics": ['engine', 'sparring', 'slowrenju'],
        "first_use_of": [],
        "aliases": ['SlowRenju', 'wind23 SlowRenju', 'Gomocup SlowRenju'],
        "section": 'engines',
    },
    {
        "id": 'pentazen',
        "title": 'PentaZen — alpha-beta Gomoku/Renju engine',
        "authors": ['schibir'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/schibir/PentaZen',
        "arxiv": None,
        "abstract": '',
        "why": 'Strong open-source alpha-beta engine (Gomocup 2021 version). Speaks Gomocup and partial Yixin protocols. GPL-3.0; can be paired with c-gomoku-cli for batch games.',
        "topics": ['engine', 'sparring', 'pentazen'],
        "first_use_of": [],
        "aliases": ['PentaZen', 'schibir PentaZen', 'PentaZen engine'],
        "section": 'engines',
    },
    {
        "id": 'chis',
        "title": 'Chis — Gomoku AI engine',
        "authors": ['ChisBread'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/ChisBread/Chis',
        "arxiv": None,
        "abstract": '',
        "why": 'C++ Gomoku engine producing a Piskvork-compatible executable. MPL-2.0; mid-tier sparring partner via the Gomocup protocol.',
        "topics": ['engine', 'sparring', 'chis'],
        "first_use_of": [],
        "aliases": ['Chis', 'ChisBread Gomoku', 'Chis engine'],
        "section": 'engines',
    },
    {
        "id": 'z2i',
        "title": 'Z2I — AlphaZero-style Gomoku engine',
        "authors": ['Joker2770'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/Joker2770/Z2I',
        "arxiv": None,
        "abstract": '',
        "why": 'MIT-licensed MCTS+ONNX engine supporting freestyle, standard, renju and caro, with Python training scripts. Less strong than Rapfi/KataGomo but permissively licensed and includes selfplay training.',
        "topics": ['engine', 'sparring', 'data generator', 'z2i'],
        "first_use_of": [],
        "aliases": ['Z2I', 'Joker2770 Z2I', 'Z2I Gomoku'],
        "section": 'engines',
    },
    {
        "id": 'nut-engine',
        "title": 'Nut-engine — Gomocup protocol engine',
        "authors": ['winterdl'],
        "year": None,
        "venue": 'GitHub',
        "doi": None,
        "url": 'https://github.com/winterdl/Nut-engine',
        "arxiv": None,
        "abstract": '',
        "why": 'Apache-2.0 Gomoku/Renju AI supporting the Gomocup protocol. Mid-tier sparring partner; permissive license makes it safe for integration tests.',
        "topics": ['engine', 'sparring', 'nut-engine'],
        "first_use_of": [],
        "aliases": ['Nut-engine', 'winterdl Nut-engine', 'Nut engine Gomoku'],
        "section": 'engines',
    },
]





def fmt_authors(authors):
    return ", ".join(authors)


def fmt_link(ref):
    if ref.get("arxiv"):
        return f"https://arxiv.org/abs/{ref['arxiv']}"
    if ref.get("doi"):
        return f"https://doi.org/{ref['doi']}"
    return ref.get("url", "")


def generate_catalogue():
    lines = []
    lines.append("# rust-ml Reference Catalogue\n")
    lines.append("## Abstract\n")
    lines.append("This document is the canonical literature reference for the rust-ml Gomoku/AlphaZero project. "
                 "It lists every external paper, thesis, rule source, verified dataset, open-source engine, "
                 "chapters, tutorials, and code comments should cite when they use a pointy term such as "
                 "PUCT, UCB1, threat-space search, or root Dirichlet noise. Each entry gives a full citation, "
                 "a one-line reason the project cites it, a stable URL, and—where applicable—the "
                 "\"first noteworthy use of\" tag that pins the term to its original source.\n")
    lines.append("## Glossary\n")
    lines.append("- **First noteworthy use** — the earliest citable source that introduced or made standard "
                 "a term or mechanism in the form the project uses it. It is not necessarily the absolute "
                 "first mention in print; it is the source future writing should point to.\n")
    lines.append("- **MCTS** — Monte Carlo Tree Search: the four-phase select/expand/evaluate/backup algorithm.\n")
    lines.append("- **UCT/PUCT** — selection rules that use upper-confidence bounds; PUCT adds a prior.\n")
    lines.append("- **TSS** — threat-space search, the forcing-move proof method for Gomoku.\n")
    lines.append("- **VCF/VCT** — Victory by Continuous Four / Victory by Continuous Threat (standard Gomoku/Renju "
                 "terminology; no single citable origin was verified for this catalogue).\n")
    lines.append("- **Local** — a document inside this repository's `docs/` tree.\n")
    for sec_key, sec_title in SECTIONS:
        section_refs = [r for r in REFS if r.get("section") == sec_key]
        if not section_refs:
            continue
        lines.append(f"## {sec_title}\n")
        for ref in section_refs:
            lines.append(fmt_entry(ref))
    return "\n".join(lines)


def fmt_entry(ref):
    lines = []
    lines.append(f"**{fmt_authors(ref['authors'])} ({ref['year']}).** *{ref['title']}*.{(' ' + ref['venue'] + '.') if ref['venue'] else ''}")
    if ref.get("unverified"):
        lines.append("- **unverified** — bibliographic details could not be fully confirmed against a publisher record.")
    if ref.get("link_unverified"):
        lines.append("- **link unverified** — the DOI/publisher page returned a non-200 status (or a WAF challenge) during curl checking; the DOI itself is recorded correctly.")
    lines.append(f"- Why this project cites it: {ref['why']}")
    link = fmt_link(ref)
    if link:
        lines.append(f"- Link: {link}")
    if ref.get("first_use_of"):
        tag = ", ".join(ref["first_use_of"])
        lines.append(f"- First noteworthy use of: {tag}")
    lines.append("")
    return "\n".join(lines)


def generate_index():
    out = []
    for ref in REFS:
        row = {
            "id": ref["id"],
            "title": ref["title"],
            "authors": ref["authors"],
            "year": ref["year"],
            "venue": ref["venue"],
            "url": fmt_link(ref),
            "arxiv": ref.get("arxiv") or "",
            "abstract": ref.get("abstract", ""),
            "aliases": list(dict.fromkeys(ref.get("aliases", []) + ref.get("first_use_of", []))),
            "topics": ref.get("topics", []),
            "first_use_of": ref.get("first_use_of", []),
        }
        out.append(json.dumps(row, ensure_ascii=False))
    return "\n".join(out) + "\n"


def main():
    catalogue = generate_catalogue()
    with open("catalogue.md", "w", encoding="utf-8") as f:
        f.write(catalogue)
    print("Wrote catalogue.md")

    index = generate_index()
    with open("index.jsonl", "w", encoding="utf-8") as f:
        f.write(index)
    print("Wrote index.jsonl")


if __name__ == "__main__":
    main()
